### ISSUE TITLE
setup failed - greenstack missing

### ISSUE THREAD

**Issue by keredson** [tbodt/v8py#3]
```
$ pip3 install v8py
Collecting v8py
  Downloading v8py-0.9.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5wosv1yh/v8py/setup.py", line 28, in <module>
        import greenstack
    ImportError: No module named 'greenstack'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5wosv1yh/v8py/
```

**Comment by tbodt** [comment]
For now, `pip install greenstack`. I'll look for a fix.

**Comment by keredson** [comment]
yep, that's what i did.  just documenting.  thanks!

**Comment by tbodt** [comment]
https://github.com/tbodt/v8py/commit/87413e3126911ecbddf853223051ab6c3119cbc6 should fix this, assuming it passes CI

**Comment by tbodt** [comment]
All fixed. Also upgraded to V8 5.9 and deployed latest changes to pypi
